version: '3.8'

services:
  streamlit-agregador:
    build:
      context: . # O contexto de construção é o diretório atual (onde o Dockerfile está no repositório clonado)
      dockerfile: Dockerfile # O nome do seu Dockerfile
    image: ricardosousaib/inobest-tools:latest # Este nome é para TAGGEAR a imagem construída localmente
    container_name: inobest-tools-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    # volumes:
    #   - /caminho/no/seu/servidor/para/dados:/app/data
    # environment:
    #   - VARIAVEL_DE_AMBIENTE=valor
